[tool.poetry]
name = "thesis"
version = "0.1.0"
description = ""
authors = ["Ditrip <shpak.mitia2014@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.1,<=3.10.12"
mlagents = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
